"""add skill subheading description github_url

Revision ID: b3316016bbdd
Revises: oo1p2q3r4s5t
Create Date: 2026-06-18 21:22:03.416571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b3316016bbdd'
down_revision: Union[str, None] = 'oo1p2q3r4s5t'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_fired', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_alert_fired_created_at')

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('app_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_app_tokens_token')
        batch_op.create_index(batch_op.f('ix_app_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_posts_service_key'), ['service_key'], unique=False)

    with op.batch_alter_table('hotel_crawl_records', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('hotel_crawl_sessions', schema=None) as batch_op:
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('job_crawl_records', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('job_crawl_sessions', schema=None) as batch_op:
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_news_items_created_at')
        batch_op.drop_index('ix_news_items_source')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subheading', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('stream_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_stream_events_created_at')

    with op.batch_alter_table('stream_topics', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_stream_topics_name')
        batch_op.create_index(batch_op.f('ix_stream_topics_name'), ['name'], unique=True)

    with op.batch_alter_table('ude_records', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('ude_sessions', schema=None) as batch_op:
        batch_op.alter_column('source_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ude_sessions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('source_config',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('ude_records', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('stream_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_topics_name'))
        batch_op.create_index('ix_stream_topics_name', ['name'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('stream_events', schema=None) as batch_op:
        batch_op.create_index('ix_stream_events_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('description')
        batch_op.drop_column('subheading')

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('ix_news_items_source', ['source'], unique=False)
        batch_op.create_index('ix_news_items_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('job_crawl_sessions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('job_crawl_records', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('hotel_crawl_sessions', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('analytics_spec',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('hotel_crawl_records', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_service_key'))
        batch_op.drop_column('service_key')

    with op.batch_alter_table('app_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_tokens_token'))
        batch_op.create_index('ix_app_tokens_token', ['token'], unique=False)

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('alert_fired', schema=None) as batch_op:
        batch_op.create_index('ix_alert_fired_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
