"""blog likes, comments, featured

Revision ID: da1daa73c50a
Revises: b065094ad9ba
Create Date: 2026-06-08 13:54:47.932924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1daa73c50a'
down_revision: Union[str, None] = 'b065094ad9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comments',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_comments_post_id'), ['post_id'], unique=False)

    op.create_table('blog_likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_likes_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_likes_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('like_count')
        batch_op.drop_column('is_featured')

    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_blog_likes_fingerprint'))

    op.drop_table('blog_likes')
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_comments_post_id'))

    op.drop_table('blog_comments')
    # ### end Alembic commands ###
